#pragma config(Motor,  port1,           backLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port2,           backRightMotor, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port9,           frontLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          frontRightMotor, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		
		int Fore= (vexRT[Ch3]/3);
		int Side=(vexRT[Ch4]/3);
		int Rot=(vexRT[Ch1]/3);

		motor[frontLeftMotor] = Fore + Side + Rot;
		motor[frontRightMotor] = Fore - Side + Rot;
		motor[backLeftMotor] = -Fore + Side + Rot;
		motor[backRightMotor] = -Fore - Side + Rot;
		
	}

}
