#pragma config(Motor,  port1,           frontRightMotor, tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port2,           frontLeftMotor, tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port9,           backRightMotor, tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port10,          backLeftMotor, tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		
		int Fore = vexRT[Ch3] / 3;
		int Side = vexRT[Ch4] / 3;
		int Rot = vexRT[Ch1] / 3;

		motor[frontRightMotor] = -Fore + Side + Rot;
		motor[frontLeftMotor] = -Fore - Side - Rot;
		motor[backRightMotor] = Fore + Side - Rot;
		motor[backLeftMotor] = Fore - Side + Rot;
		
	}

}
