//TODO: Motor peripheral config

task main()
{
    while(true)//Loop infinitely
    {
        motor[leftMotor] = (vexRT[CH3] / 2) - (vexRT[CH4] / 2);//Magic - not verified, so ignore the subtraction for now
        motor[rightMotor] = (vexRT[CH3] / 2) - (vexRT[CH4] / 2);
        
        if(vexRT[Btn5U])//If R1 is pressed...
            motor[armMotor] = 40;//Move the arm up...
        else if(vexRT[Btn5D])//If R2 is pressed instead...
            motor[armMotor] = -40;//Move the arm down...
        else//Otherwise...
            motor[armMotor] = 0;//Stop the arm
        
        if(vexRT[Btn6U])//If L1 is pressed...
            motor[clawMotor] = 40;//Close the claw...
        else if(vexRT[Btn6D])//If L2 is pressed...
            motor[clawMotor] = -40;//Open the claw...
        else//Otherwise...
            motor[clawMotor] = 0;//Halt claw movement
        
    }
}
