#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  rightSonar,     sensorSONAR_mm)
#pragma config(Sensor, dgtl3,  midSonar,       sensorSONAR_mm)
#pragma config(Sensor, dgtl5,  leftSonar,      sensorSONAR_mm)
#pragma config(Sensor, dgtl7,  liftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  qEncBL,         sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  qEncBR,         sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  qEncFR,         sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  qEncFL,         sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_5,  servoEnc,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           frontRightMotor, tmotorVex393_MC29, openLoop, driveRight, encoderPort, I2C_3)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorVex393_MC29, openLoop, reversed, driveLeft, encoderPort, I2C_4)
#pragma config(Motor,  port4,           backRightMotor, tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port5,           backLeftMotor, tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port6,           scissorRight,  tmotorVex393_MC29, openLoop, driveRight, encoderPort, dgtl7)
#pragma config(Motor,  port7,           scissorLeft,   tmotorVex393_MC29, openLoop, driveLeft, encoderPort, dgtl7)
#pragma config(Motor,  port8,           impServ,       tmotorVex393_MC29, openLoop, encoderPort, I2C_5)
#pragma config(Motor,  port9,           clawMot,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(I2C_Usage, I2C1, i2cSensors)
//#pragma config(Sensor, I2C_1,  qEncBL,         sensorQuadEncoderOnI2CPort,    , AutoAssign)
//#pragma config(Sensor, I2C_2,  qEncBR,         sensorQuadEncoderOnI2CPort,    , AutoAssign)
//#pragma config(Sensor, I2C_3,  qEncFR,         sensorQuadEncoderOnI2CPort,    , AutoAssign)
//#pragma config(Sensor, I2C_4,  qEncFL,         sensorQuadEncoderOnI2CPort,    , AutoAssign)
//#pragma config(Motor,  port2,           backLeftMotor, tmotorVex393_MC29, PIDControl, reversed, driveRight, encoderPort, I2C_2)
//#pragma config(Motor,  port3,           frontLeftMotor, tmotorVex393_MC29, PIDControl, reversed, driveLeft, encoderPort, I2C_3)
//#pragma config(Motor,  port4,           frontRightMotor, tmotorVex393_MC29, PIDControl, reversed, driveRight, encoderPort, I2C_4)
//#pragma config(Motor,  port5,           backRightMotor, tmotorVex393_MC29, PIDControl, reversed, driveLeft, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//Robot B [Small]


#include "common\move.h"
#include "small\improvServo.h"

#pragma platform(VEX)




task main()
{
	startTask(manageServo);
	gDesServAng = 45;
	delay(1500);
	gDesServoAng = 90;
	//moveForward(12);
	while(1);
}

//task main()
//{
//	moveForward(12);
//	alignBot();
//	pickupBlock();
//	moveForward(16);
//	moveRotate(-PI / 2);
//	alignBot();
//	pickupBlock();
//	moveForward(23);
//	alignBot();
//	pickupBlock();
//}

//
