#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  qEncBL,         sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  qEncBR,         sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  qEncFR,         sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  qEncFL,         sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           backLeftMotor, tmotorVex393_MC29, PIDControl, reversed, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorVex393_MC29, PIDControl, reversed, driveLeft, encoderPort, I2C_3)
#pragma config(Motor,  port4,           frontRightMotor, tmotorVex393_MC29, PIDControl, reversed, driveRight, encoderPort, I2C_4)
#pragma config(Motor,  port5,           backRightMotor, tmotorVex393_MC29, PIDControl, reversed, driveLeft, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "common\move.h"

#pragma platform(VEX)




task main()
{
	while(1)
	{
		//moveForward(24);
		for(int i = 4; i > 0; i--)
		{
			moveRotate(PI/2);
			sleep(1500);
		}

		for(int i = 2; i > 0; i--)
		{
			moveRotate(PI);
			sleep(1500);
		}

		moveRotate(2*PI);
		sleep(2500);
	}
}
